<?php

namespace CarlBennett\MVC\Templates;

?><!DOCTYPE html>
<html lang="en-US">
  <head>
    <title><?php echo $title; ?></title>
    <link rel="icon" href="/favicon.ico" type="image/png" sizes="48x48"/>
<?php if (!empty($keywords)) { ?>
    <meta name="keywords" content="<?php echo $keywords; ?>"/>
<?php } ?>
<?php if (!empty($description)) { ?>
    <meta name="description" content="<?php echo $description; ?>"/>
    <meta property="og:description" content="<?php echo $description; ?>"/>
    <meta property="twitter:description" content="<?php echo $description; ?>"/>
<?php } ?>
  </head>
  <body>
    <header>php-mvc</header>
    <main>
